The application structure and functionality
softberg/quantum-react-front pull request #1
Opened 2022-09-02 15:03 UTC by hatik92

2022-09-02 17:22 UTC, armanist requested changes

2022-09-02 17:22 UTC, armanist commented on .env.example
> +REACT_APP_API_URL="backEnd url"
What this constant is for : REACT_APP_API_URL ?

2022-09-02 17:22 UTC, armanist commented on .gitignore
> +
Ignore the package-lock.json

2022-09-02 17:22 UTC, armanist commented on public/custom.js
> +jQuery(document).ready(function ($) {
Why do we need jQuery do be used??

2022-09-02 17:22 UTC, armanist commented on public/index.html
> +      Notice the use of %PUBLIC_URL% in the tags above.
Remove all unnecessary comments

2022-09-02 17:22 UTC, armanist commented on public/manifest.json
> +{
What this file is doing?

2022-09-02 17:22 UTC, armanist commented on public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
What this file is doing?

2022-09-02 17:22 UTC, armanist commented on src/App.js
> +import Posts from './components/Posts/Posts';
Why it's needed to create folders for each single file components?

2022-09-02 17:22 UTC, armanist commented on src/App.test.js
> +import { render, screen } from '@testing-library/react';
Does this test working?

2022-09-02 17:22 UTC, armanist commented on src/api/api.js
> +		// 	return
Remove unnecessary comments

2022-09-02 17:22 UTC, armanist commented on src/api/api.js
> +					return await apiConfig.post(url + token, postDataOrGetParam)
Why we pass token, if the route is without token?

2022-09-02 17:22 UTC, armanist commented on src/api/api.js
> +					return await apiConfig.post(url, postDataOrGetParam)
Why we do post if we are in put block?

2022-09-02 17:22 UTC, armanist commented on src/components/Home/Home.jsx
> +		<ul className="bg-bubbles">
Bubbles can be moved to separate component

2022-09-02 17:22 UTC, armanist commented on src/components/About/About.jsx
> +			<ul className="bg-bubbles">
Bubbles can me moved to separate component

2022-09-02 17:22 UTC, armanist commented on src/components/Auth/RequireAuth.js
> +		localStorage.getItem("isAuth")
Make sure the isAuth really needed

2022-09-02 17:22 UTC, armanist commented on src/components/Auth/SignIn.jsx
> +					case "inactive_account":
No need to check the message, it's back-end issue

2022-09-02 17:22 UTC, armanist commented on src/reportWebVitals.js
> +const reportWebVitals = onPerfEntry => {
What this file doing?

2022-09-02 17:22 UTC, armanist commented on src/setupTests.js
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
Is this file needed?

2022-09-05 08:16 UTC, hatik92 commented on public/manifest.json
> +{
The manifest.json provides information about a web application in a JSON text file, necessary for the web app to be downloaded and be presented to the user similarly to a native app (e.g., be installed on the homescreen of a device, providing users with quicker access and a richer experience). PWA manifests include its name, author, icon(s), version, description, and list of all the necessary resources (among other things).

2022-09-05 15:40 UTC, armanist approved these changes

2022-09-14 12:25 UTC, armanist approved these changes

2022-09-14 12:29 UTC, merged