bugs fixex and ui changes
softberg/quantum-react-front pull request #3
Opened 2023-01-11 14:12 UTC by Stepanwdr

2023-01-19 09:55 UTC, armanist requested changes
There are lots of files that are not getting actually changed but appeared in git all those files need to be reverted and only the actual changes should be kept.

Also remove `.idea` related files

2023-01-19 09:55 UTC, armanist commented on public/index.html
> -	<noscript>You need to enable JavaScript to run this app.</noscript>
What is the change here?

2023-01-19 09:55 UTC, armanist commented on src/assets/locales/am/common.json
> -{
can not see any difference here

2023-01-19 09:55 UTC, armanist commented on src/assets/locales/am/validation.json
> -{
can not see any difference here

2023-01-19 09:55 UTC, armanist commented on src/assets/locales/en/common.json
> -{
can not see any difference here

2023-01-19 09:55 UTC, armanist commented on src/components/Auth/ActivatePage.jsx
> -import { useEffect } from 'react'
can not see any difference here

2023-01-19 09:55 UTC, armanist commented on src/components/Auth/ActivatePage.jsx
> -import { authApi } from './../../api/authApi';
can not see any difference here

2023-01-19 12:13 UTC, hatik92 approved these changes

2023-01-25 13:34 UTC, Stepanwdr commented on public/index.html
> -	<noscript>You need to enable JavaScript to run this app.</noscript>
its will not be in the next commit

2023-01-25 15:15 UTC, armanist approved these changes

2023-01-25 15:16 UTC, merged